### ISSUE TITLE
クラッシュレポート無効化設定の更新

### ISSUE THREAD

**Issue by myokoym** [mozilla-japan/enterprise#14]
[クラッシュ時の情報を送信させたくない](https://www.mozilla.jp/business/faq/tech/security/#faq2)の項で、Windowsのレジストリキーを設定してクラッシュレポータが非表示になることを検証したところ、無効化されずにクラッシュレポータが表示されてしまった。他の方法も試したが、無効化できる手順は見つかっていない。

検証した方法は以下の4通り。どれもクラッシュレポータが表示されてしまった。
- レジストリキー`KEY_CURRENT_USER\Software\Mozilla\Firefox\Crash Reporter`に`0`を設定
- オプションの詳細＞データの詳細＞クラッシュレポートの送信を有効にするのチェックをはずす
- インストールディレクトリにoverride.iniを作成し、`[Crash Reporter]`に`Enable=0`を設定
- application.iniの`[Crash Reporter]`の`Enable=1`を`Enable=0`に変更

確認に使用したFirefox: ESR 45.1.0
クラッシュさせた手順: [Firefoxを意図的にクラッシュさせる方法 - ククログ(2015-12-14)](http://www.clear-code.com/blog/2015/12/14.html)

**Comment by piroor** [comment]
もしFirefox 38では再現しないのであれば45での後退バグということになるので、Firefox 38での検証も必要ですね。

**Comment by myokoym** [comment]
Firefox 38（ESR 38.8.0）でも再現しました。45同様、上記の設定をしてもクラッシュレポータが表示されてしまいます。

**Comment by myokoym** [comment]
まだ試していなかった環境変数`MOZ_CRASHREPORTER_DISABLE`に`1`を設定する方法を試したところ、上記の4通りとは異なり、「Firefox は動作を停止しました」のダイアログが出てしまいました。クラッシュレポータは表示されませんでしたが、期待される挙動ではなさそうです。

環境変数の値を0などに変えて試しても、同様に「Firefox は動作を停止しました」のダイアログが出てクラッシュレポータが表示されない状態になりました。

上記の挙動はFirefox 38、45とも同じでした。

**Comment by piroor** [comment]
1227722 – Disabling the crash reporter no longer works.
https://bugzilla.mozilla.org/show_bug.cgi?id=1227722

**Comment by piroor** [comment]
#25 にはこの件の修正も含まれます。
