### ISSUE TITLE
Customizable Shortcutsについての記述を削除する

### ISSUE THREAD

**Issue by myokoym** [mozilla-japan/enterprise#16]
https://www.mozilla.jp/business/faq/tech/user-control/#faq1 に個人利用なら有用との記述があるが、開発が終了しているようなので削除する。

アドオンページから削除され、「このアドオンは作者によって削除されました。 」と表示されている。
https://addons.mozilla.org/ja/firefox/addon/customizable-shortcuts/

GitHubにも[DISCONTINUED]との記述がある。
https://github.com/ttaubert/customizable-shortcuts

**Comment by piroor** [comment]
了解です。ではこの記述は削除で。

**Comment by myokoym** [comment]
「Keybinder」というアドオンがあるようなので、差し替えるのもありかもしれません。

* [Mozilla Re-Mix: Firefoxのショートカットキーを簡単に変更することができるアドオン「Keybinder」](http://mozilla-remix.seesaa.net/article/415491610.html)

**Comment by myokoym** [comment]
メモ: KeybinderはCustomizable Shortcutsをフォークして作られている
[Lord-Kamina/keybinder: Firefox add-on that allows deep customization of shortcuts. Based on Tim Taubert's "Customizable Shortcuts."](https://github.com/Lord-Kamina/keybinder)

**Comment by myokoym** [comment]
ここで個人利用について言及する必要はなさそうなので、やはり削除する方向で修正しようと思います。
