### ISSUE TITLE
Windows の証明書ストアを使えるようになる件の FAQ が欲しい

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/enterprise#21]
Firefox 49 からは security.enterprise_roots.enabled = true にすることで Firefox 独自では無く Windows の証明書ストアを TLS サーバの証明書検証に利用可能になる件に関する FAQ を追加できると良いかも。

記事だけさらっと見て分かりにくい or 良く分かんなかったポイント
- Windows 側に登録した自社のオレオレ証明書も信用対象になるんだよね？
- 独自ストアと Windows ストアと両方が同時利用されるのか丸ごと差し替えられるのか
- security.enterprise_roots.enabled をさわらない限り一般ユーザへの影響はない？
- ついでに GPKI とか LGPKI もこれで (彼らの対応を待たずに) 使える？
- Windows 8.1 の Microsoft Family Safety 機能も使えるようになるらしいけど何それ
- Mac/Linux については？

reference:
https://mike.kaply.com/2016/09/01/upcoming-changes-to-root-certificates-in-firefox-on-windows/
http://news.softpedia.com/news/firefox-changes-root-certificate-handling-procedures-on-windows-507907.shtml

**Comment by piroor** [comment]
Bugzillaでの議論とパッチを見て現状で判明している点は以下の通りです。

 * 今回の変更はビルドオプションでWindowsでのみ有効になる箇所なので、Linux/macOS（OS X）には影響しない。
 * 認識するのはルート証明書（認証局証明書）のみである模様。サイト証明書、クライアント証明書には関係しない。
 * Windowsの証明書ストアだけを使うようになるのではなく、独自の証明書ストア＋Windowsの証明書ストアになる。

**Comment by piroor** [comment]
弊社のブログ記事として現状把握していた事をまとめてみました。
http://www.clear-code.com/blog/2017/6/1.html

**Comment by piroor** [comment]
#25 にはこの件についての言及も含まれます。
