### ISSUE TITLE
ビルド結果と現状の mozilla.jp コードが一致しない

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/enterprise#23]
以前使われていたビルドスクリプトをこちらのリポジトリに入れ、Netlify 使って自動ビルドするよう設定してみた (コミットしたら自動ビルドして更新されます)
https://mozilla-japan-enterprise.netlify.com/dist.zip
のだが、生成されたファイルが
https://github.com/mozilla-japan/mozilla.jp/tree/master/business/faq/tech 
配下のものと異なる:
https://gist.github.com/dynamis/6d961261eb23c089a356b01a37a098c3

ぱっと見では templates https://github.com/mozilla-japan/enterprise/tree/master/templates の差分ばかりっぽいので templates の更新だけで済みそうにも見えるので、そうすれば使えそう。ついでにデザインなど変えるなどしても良いですし。

@kyoshino mozilla.jp 公開用に変換した時って templates 自体を書き換えてからビルドしてました？それとももしかしたら出力後に他のファイルと一緒に一括置換とかしてました？

**Comment by piroor** [comment]
テンプレートを修正してビルドして比較していますが、どう編集しても同じにならない様子です。ビルド後のファイルを直接書き換えられたのではないかと思われます。
今の https://github.com/mozilla-japan/mozilla.jp/tree/master/business/faq/tech を原本としてこちらに反映する、というのは現実的ではないかも知れません。

**Comment by kyoshino** [comment]
随分前の話でよく覚えてませんが、ビルド後に一部手作業で書き換えたかもしれません。いずれにしても、まずは https://www.mozilla.jp/business/faq/tech/ をそのまま使い続けるか考えたほうが良いのでは... @dynamis には前回ミーティングで話したんですが、全体的に書き換えが必要なら、この機会に GitHub 上の Wiki なり GitHub Pages なり別の場所に移して更新しやすくしても良いんじゃないでしょうか。

**Comment by kyoshino** [comment]
随分前の話でよく覚えてませんが、ビルド後に一部手作業で書き換えたかもしれません。いずれにしても、まずは https://www.mozilla.jp/business/faq/tech/ をそのまま使い続けるか考えたほうが良いのでは... @dynamis には前回ミーティングで話したんですが、全体的に書き換えが必要なら、この機会に GitHub 上の Wiki なり GitHub Pages なり別の場所に移して更新しやすくしても良いんじゃないでしょうか。

**Comment by piroor** [comment]
はい、内容の全面更改は必要という点は認識しています。ただ、一気に全部作り直すというやり方だと落とし所を見つけにくいのではないかと思っていて、

1. FAQ.mdをソースとしてHTMLを生成→サイトに反映 というワークフローを回せる状態に戻す。（生のHTMLを触るのは避けたい）
2. FAQの中で明らかにdeprecated/obsoleteになっている部分を個別に削除・更新する。
3. 全体の構成をより分かりやすい物に改める。

と少しずつ進めてソフトランディングを目指すのが安全ではないかと考えています。いかがでしょうか？

**Comment by piroor** [comment]
関連する変更として、FAQのESR68向けの最低限の更新を #25 として提案中です。

**Comment by dynamis** [comment]
コメント書けておらず申し訳ないです。

ローカルで動作テスト可能に https://github.com/mozilla-japan/mozilla.jp/pull/5 なども見て、本当はちゃんと CI セットアップして手元に Apache など立てずに済ませられるようにすべきなんだろうけど PHP コードだからちょっと面倒だな、コミュニティなどで運用する時にはどうするのが良いのかなと少し考えていたところで止まってました。

方針は賛成ですし、一連の issue や PR ざっと見ましたが基本的に問題無いというかどんどん Piro さんオーナーシップ持って進めて頂いて構わないと思います。

**Comment by piroor** [comment]
とりあえずこちらのリポジトリの側のPR 2件はマージしました。
mozilla.jpについては自分は権限を持っていないので、どなたか https://github.com/mozilla-japan/mozilla.jp/pull/5 についてレビューおよびマージの検討をして頂けると幸いです。
（Apacheを要求するなどいまいちな感じではあるのですが、「ベストではないが（動かしようが無いよりは）ベター」ということで。）

**Comment by dynamis** [comment]
mozilla.jp repo の admin (少なくとも write) 権限設定が webdev チームに付与されているべきところが read 権限になってしまっていたので admin 権限に変更しました。

https://github.com/orgs/mozilla-japan/teams/webdev/members

先日コードをぱっと見高桐問題無さそうには思うのですが、まだ実動作確認していないので取り急ぎマージはすぐ動作確認いただける方 or piro さんが直接実行でお任せします。

**Comment by piroor** [comment]
気付けば1ヵ月が過ぎていましたが、特にコメントがついていなかったのでマージしてしまいました。
あとは実際のサイトへのデプロイということになると思うのですが、これは今はどなたか権限がある方が手動で操作されてる感じなのでしょうか？

**Comment by dynamis** [comment]
以前は毎時 0 分の自動反映だったのですが、現在止まってますね。
サーバ管理者に確認してもらいます。

**Comment by kudodo** [comment]
本件、対応遅くなってしまい申し訳ありません。
https://www.mozilla.jp/business/faq/tech/ 更新しました。
念のため古いのはhttp://mz-jp191.naist.jp/business/faq/tech_old20200417/ で一時的に見比べられるようにしておきました。ご査収下さい。

自動更新が止まっているのと、アップロード時に一部正しく表示されるために手動で修正しています。(FreeBSDのサーバとの問題なのか、PHPのエラーがでて画面下部のナビゲーション部分が表示されない）

> Apr 17 15:14:28 mz-jp191 php-fpm[26491]: PHP Fatal error:  Uncaught Error: Call to a member function build_breadcrumbs() on null in /data/www/www.mozilla.jp/doc/includes/templates/sandstone/default-footer.inc.php:5
Apr 17 15:14:28 mz-jp191 php-fpm[26491]: Stack trace:
Apr 17 15:14:28 mz-jp191 php-fpm[26491]: #0 /data/www/www.mozilla.jp/doc/business/faq/tech/addons/index.php(194): include_once()
Apr 17 15:14:28 mz-jp191 php-fpm[26491]: #1 {main}
Apr 17 15:14:28 mz-jp191 php-fpm[26491]:   thrown in /data/www/www.mozilla.jp/doc/includes/templates/sandstone/default-footer.inc.php on line 5


コンテンツのビルドに関してもnode.jsが12だとReferenceError: primordials is not defined 等というエラーがでてビルドできなかったので、ググった範囲ででてきたgulpを4系にするというのも試しましたが動かず最終的にnode.jsを11系にバージョンダウンして解決しています。（OSは最終的に手元のUbuntu18.04LTSを利用)。

**Comment by piroor** [comment]
対応ありがとうございます！
リンク先を見ると https://www.mozilla.jp/business/faq/tech/addons/#faq1 等がFile Not Foundになっていました。
https://mozilla.jp/business/faq/tech/addons/#faq1 （www.なし）だと見られるのですが、これは何かリポジトリ側での作業が必要でしょうか？
それとも、デプロイのオペレーションで対応頂く必要がある感じでしょうか？

**Comment by kyoshino** [comment]
作業が遅くなりましたが、www.mozilla.jp を全ページ Markdown の静的サイトに切り替えました。今後は https://github.com/mozilla-japan/www.mozilla.jp/tree/main/content/business/faq/tech 以下のファイルを更新すれば、自動的に Netlify でビルド・デプロイされます。この別レポジトリは必要なくなったのでアーカイブしましょう。
